#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep "DVI-D-0 connected") ]];
then
	xrandr --output DisplayPort-0 --off --output HDMI-A-0 --primary --mode 1920x1080 --pos 1366x0 --rotate normal --output DVI-D-0 --mode 1366x768 --pos 0x353 --rotate normal
	bspc monitor HDMI-A-0 -d 6 7 8 9 10
	bspc monitor DVI-D-0 -d 1 2 3 4 5
fi

xsetroot -cursor_name left_ptr &
/usr/lib/polkit-kde-authentication-agent-1 &
dunst &
compfy -b &
nitrogen --restore &
/home/pien/.config/polybar/scripts/launch.sh &
python /home/pien/.config/scripts/notificationimg.sh &
wmname LG3D &

bspc config border_width         1
bspc config window_gap          12

bspc config focused_border_color '#b18fbf'
bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
#bspc config click_to_focus true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config external_rules_command "/home/pien/.config/bspwm/external_rules"
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Spotify desktop='^6'
bspc rule -a youtube-music desktop='^6'
bspc rule -a "Zotero":Toplevel state=floating
bspc rule -a Steam:*:"Friends List" state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Windscribe state=pseudo_tiled
